### ISSUE TITLE
TitleBar のフォーカス中ファイル表示を有効化する 

### ISSUE THREAD

**Issue by Sota-Watanabe** [cdlab-sit/XenonText#19]
エディット画面の完成後に以下の部分を変更し, フォーカスしているフォルダをTitleBarに表示できるようにする。
https://github.com/cdlab-sit/editor/blob/0bd5da4ce50f9983b83acdddb1fc7f5d34075705/src/renderer/components/TitleBar.jsx#L3-L5

**Comment by kawapoo** [comment]
#67 で実装済み
